### ISSUE TITLE
OIDC issue: 401 Unauthorized

### ISSUE THREAD

**Issue by matzew** [knative-extensions/eventing-integrations#31]
Using @christophd latest "debug" image for the `timer-source` I am getting this `IntegrationSource` on my reconciler-test:

```yaml
apiVersion: sources.knative.dev/v1alpha1
kind: IntegrationSource
metadata:
  annotations:
    sources.knative.dev/creator: kubernetes-admin
    sources.knative.dev/lastModifier: kubernetes-admin
  creationTimestamp: "2024-10-21T12:17:01Z"
  generation: 1
  name: integrationsource-kpcslidz
  namespace: test-rrqxffxo
  resourceVersion: "12444"
  uid: 0cf3f6d4-c816-4959-83c7-2d9525ed1c0a
spec:
  sink:
    CACerts: |-
      -----BEGIN CERTIFICATE-----
      MIIBcDCCARegAwIBAgIRAKmcp4nS3+W8ZCuS2HJFnK4wCgYIKoZIzj0EAwIwGDEW
      MBQGA1UEAxMNc2VsZnNpZ25lZC1jYTAeFw0yNDEwMjExMjE2MjNaFw0yNTAxMTkx
      MjE2MjNaMBgxFjAUBgNVBAMTDXNlbGZzaWduZWQtY2EwWTATBgcqhkjOPQIBBggq
      hkjOPQMBBwNCAAT3Lx1JIL2OhyNrUaMjfC/JjH42DpFpd+LazuM9Tc5U7RxMQjvs
      NSV3IxFvHX8TCakOAL4iX5T/C/BxiEQr1ShIo0IwQDAOBgNVHQ8BAf8EBAMCAqQw
      DwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUhmI70QbD9xQITjRBFwh+lfi+i3sw
      CgYIKoZIzj0EAwIDRwAwRAIgIAeO3d0XgC+FLpWfLK1wXtzIxPKyFewR9L2YXZ0e
      Da4CID9KbBqiR6ScUCdbNINyDcHM+MXEPCPmpbt14bpR/uBP
      -----END CERTIFICATE-----
    audience: audience
    ref:
      apiVersion: v1
      kind: Service
      name: sink-ixepwupp
      namespace: test-rrqxffxo
  timer:
    contentType: text/plain
    message: Hello, Eventing Core
    period: 2000
status:
  auth:
    serviceAccountName: kn-connector-source-integration6e92fb8ba289173693a759d48ec3e25b
  conditions:
  - lastTransitionTime: "2024-10-21T12:17:02Z"
    status: "True"
    type: ContainerSourceReady
  - lastTransitionTime: "2024-10-21T12:17:02Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-10-21T12:17:02Z"
    status: "True"
    type: ReceiveAdapterReady
  - lastTransitionTime: "2024-10-21T12:17:01Z"
    status: "True"
    type: SinkBindingReady
  observedGeneration: 1
  sinkAudience: audience
  sinkCACerts: |-
    -----BEGIN CERTIFICATE-----
    MIIBcDCCARegAwIBAgIRAKmcp4nS3+W8ZCuS2HJFnK4wCgYIKoZIzj0EAwIwGDEW
    MBQGA1UEAxMNc2VsZnNpZ25lZC1jYTAeFw0yNDEwMjExMjE2MjNaFw0yNTAxMTkx
    MjE2MjNaMBgxFjAUBgNVBAMTDXNlbGZzaWduZWQtY2EwWTATBgcqhkjOPQIBBggq
    hkjOPQMBBwNCAAT3Lx1JIL2OhyNrUaMjfC/JjH42DpFpd+LazuM9Tc5U7RxMQjvs
    NSV3IxFvHX8TCakOAL4iX5T/C/BxiEQr1ShIo0IwQDAOBgNVHQ8BAf8EBAMCAqQw
    DwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUhmI70QbD9xQITjRBFwh+lfi+i3sw
    CgYIKoZIzj0EAwIDRwAwRAIgIAeO3d0XgC+FLpWfLK1wXtzIxPKyFewR9L2YXZ0e
    Da4CID9KbBqiR6ScUCdbNINyDcHM+MXEPCPmpbt14bpR/uBP
    -----END CERTIFICATE-----
  sinkUri: https://sink-ixepwupp.test-rrqxffxo.svc.cluster.local
```

but I am getting this on my OIDC test:

```
2024-10-21 12:27:54,428 INFO  [log-action] (Camel (camel-1) thread #2 - timer://tick) Exchange[Headers: {Content-Type=text/plain}, BodyType: String, Body: Hello, Eventing Core]
2024-10-21 12:27:54,466 ERROR [org.apa.cam.pro.err.DefaultErrorHandler] (vert.x-eventloop-thread-4) Failed delivery for (MessageId: AD02669CC89028F-000000000000028B on ExchangeId: AD02669CC89028F-000000000000028B). Exhausted after delivery attempt: 1 caught: org.apache.camel.CamelException: HTTP operation failed invoking https://sink-ixepwupp.test-rrqxffxo.svc.cluster.local with statusCode: 401, statusMessage: Unauthorized

Message History (complete message history is disabled)
---------------------------------------------------------------------------------------------------------------------------------------
Source                                   ID                             Processor                                          Elapsed (ms)
source.yaml:23                           timer-source/timer-source      from[kamelet://timer-source]                                 38
	...
source.yaml:36                           timer-source/to1               knative:event/org.apache.camel.event?kind=Broker&n            0

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------: org.apache.camel.CamelException: HTTP operation failed invoking https://sink-ixepwupp.test-rrqxffxo.svc.cluster.local with statusCode: 401, statusMessage: Unauthorized
	at org.apache.camel.component.knative.http.KnativeHttpProducer.lambda$process$0(KnativeHttpProducer.java:140)
	at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:402)
	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:384)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:362)
	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:329)
	at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:291)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$7(HttpContext.java:512)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:252)
	at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:50)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)

2024-10-21 12:27:54,466 WARN  [org.apa.cam.com.tim.TimerConsumer] (vert.x-eventloop-thread-4) Error processing exchange. Exchange[AD02669CC89028F-000000000000028A]. Caused by: [org.apache.camel.CamelException - HTTP operation failed invoking https://sink-ixepwupp.test-rrqxffxo.svc.cluster.local with statusCode: 401, statusMessage: Unauthorized]: org.apache.camel.CamelException: HTTP operation failed invoking https://sink-ixepwupp.test-rrqxffxo.svc.cluster.local with statusCode: 401, statusMessage: Unauthorized
	at org.apache.camel.component.knative.http.KnativeHttpProducer.lambda$process$0(KnativeHttpProducer.java:140)
	at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:402)
	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:384)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:362)
	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:329)
	at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:291)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$7(HttpContext.java:512)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:252)
	at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:50)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

The test is essentially like: 
https://github.com/knative/eventing/blob/main/test/rekt/container_source_test.go#L107-L119

but looks like the source is unable to get the message delivered to the (generated) sink in the test

**Comment by matzew** [comment]
here is the log from the sink:

```
{"level":"info","ts":"2024-10-21T12:49:18.508Z","logger":"eventshub.event logger","caller":"logger_vent/logger.go:26","msg":"Event: \n-- EventInfo --\n--- Kind: Rejected ---\n--- Event ---\nContext Attributes,\n  specversion: 1.0\n  type: dev.knative.connector.event.timer\n  source: dev.knative.eventing.timer-source\n  subject: timer-source\n  id: AD02669CC89028F-000000000000078F\n  time: 2024-10-21T12:49:18.49Z\n  datacontenttype: text/plain\nData,\n  Hello, Eventing Core\n\n--- Error ---\ncould not get Authorization header\n--- HTTP headers ---\n  Content-Type: text/plain\n  Content-Length: 20\n  User-Agent: Vert.x-WebClient/4.5.10\n  Host: sink-ixepwupp.test-rrqxffxo.svc.cluster.local\n\n--- Status Code: 401 ---\n--- Connection ---\n{\n  \"TLS\": {\n    \"cipherSuite\": 4865,\n    \"cipherSuiteName\": \"TLS_AES_128_GCM_SHA256\",\n    \"handshakeComplete\": true\n  }\n}\n--- Origin: '10.244.0.43:40674' ---\n--- Observer: 'sink-ixepwupp' ---\n--- Time: 2024-10-21 12:49:18.49139508 +0000 UTC m=+1966.783161146 ---\n--- Sequence: 968 ---\n--- Sent Id:  ' ---\n--------------------\n"}
```

could not get Authorization header

**Comment by matzew** [comment]
The underlying deployment for the java container is like:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2024-10-21T12:17:01Z"
  generation: 4
  labels:
    sources.knative.dev/containerSource: kn-connector-source-integrationsource-kpcslidz
    sources.knative.dev/source: container-source-controller
  name: kn-connector-source-integrationsource-kpcslidz-deployment
  namespace: test-rrqxffxo
  ownerReferences:
  - apiVersion: sources.knative.dev/v1
    blockOwnerDeletion: true
    controller: true
    kind: ContainerSource
    name: kn-connector-source-integrationsource-kpcslidz
    uid: dec55e7e-312d-403c-8879-7a6864147d3c
  resourceVersion: "12457"
  uid: a294d67c-ce00-47ba-88f9-8f4ef6d5d11f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      sources.knative.dev/containerSource: kn-connector-source-integrationsource-kpcslidz
      sources.knative.dev/source: container-source-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        sources.knative.dev/containerSource: kn-connector-source-integrationsource-kpcslidz
        sources.knative.dev/source: container-source-controller
    spec:
      containers:
      - env:
        - name: CAMEL_KNATIVE_CLIENT_SSL_ENABLED
          value: "true"
        - name: CAMEL_KNATIVE_CLIENT_SSL_CERT_PATH
          value: /knative-custom-certs/knative-eventing-bundle.pem
        - name: CAMEL_KAMELET_TIMER_SOURCE_PERIOD
          value: "2000"
        - name: CAMEL_KAMELET_TIMER_SOURCE_MESSAGE
          value: Hello, Eventing Core
        - name: CAMEL_KAMELET_TIMER_SOURCE_CONTENTTYPE
          value: text/plain
        - name: CAMEL_KAMELET_TIMER_SOURCE_REPEATCOUNT
          value: "0"
        - name: K_SINK
          value: https://sink-ixepwupp.test-rrqxffxo.svc.cluster.local
        - name: K_CA_CERTS
          value: |-
            -----BEGIN CERTIFICATE-----
            MIIBcDCCARegAwIBAgIRAKmcp4nS3+W8ZCuS2HJFnK4wCgYIKoZIzj0EAwIwGDEW
            MBQGA1UEAxMNc2VsZnNpZ25lZC1jYTAeFw0yNDEwMjExMjE2MjNaFw0yNTAxMTkx
            MjE2MjNaMBgxFjAUBgNVBAMTDXNlbGZzaWduZWQtY2EwWTATBgcqhkjOPQIBBggq
            hkjOPQMBBwNCAAT3Lx1JIL2OhyNrUaMjfC/JjH42DpFpd+LazuM9Tc5U7RxMQjvs
            NSV3IxFvHX8TCakOAL4iX5T/C/BxiEQr1ShIo0IwQDAOBgNVHQ8BAf8EBAMCAqQw
            DwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUhmI70QbD9xQITjRBFwh+lfi+i3sw
            CgYIKoZIzj0EAwIDRwAwRAIgIAeO3d0XgC+FLpWfLK1wXtzIxPKyFewR9L2YXZ0e
            Da4CID9KbBqiR6ScUCdbNINyDcHM+MXEPCPmpbt14bpR/uBP
            -----END CERTIFICATE-----
        - name: K_CE_OVERRIDES
        image: quay.io/christophd/timer-source:1.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: source
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /knative-custom-certs
          name: kne-bundle-volume
          readOnly: true
        - mountPath: /oidc
          name: oidc-token
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: kne-bundle-volume
        projected:
          defaultMode: 420
          sources:
          - configMap:
              name: knative-eventing-bundlekne-bundle
      - name: oidc-token
        projected:
          defaultMode: 420
          sources:
          - secret:
              name: kn-connector-source-f9e25101bc4ab89d77066d146efad7ca-oidc-token
```

**Comment by matzew** [comment]
Token present at:
```
kubectl -n test-rrqxffxo exec -it kn-connector-source-integrationsource-kpcslidz-deployment-tg5k5  -- /bin/bash 

[jboss@kn-connector-source-integrationsource-kpcslidz-deployment-tg5k5 ~]$ cd /oidc
[jboss@kn-connector-source-integrationsource-kpcslidz-deployment-tg5k5 oidc]$ ls -la
total 0
drwxrwxrwt. 3 root root 100 Oct 21 12:47 .
drwxr-xr-x. 1 root root 108 Oct 21 12:17 ..
drwxr-xr-x. 2 root root  60 Oct 21 12:47 ..2024_10_21_12_47_12.2867474985
lrwxrwxrwx. 1 root root  32 Oct 21 12:47 ..data -> ..2024_10_21_12_47_12.2867474985
lrwxrwxrwx. 1 root root  12 Oct 21 12:17 token -> ..data/token
[jboss@kn-connector-source-integrationsource-kpcslidz-deployment-tg5k5 oidc]$ cat token 
eyJhbGciOiJSUzI1NiIsImtpZCI6IlVaVFRHOVRXYWxrUlNRaGFZdlkta1hkY0pIVTMxY1Z1ckw3QXcxaS1rUUEifQ.eyJhdWQiOlsiYXVkaWVuY2UiXSwiZXhwIjoxNzI5NTE4MzQ1LCJpYXQiOjE3Mjk1MTQ3NDUsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiNWJiNTAzY2UtZGVmOS00ZjcxLWFiM2MtYmI1YmYyOTVmZjMyIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJ0ZXN0LXJycXhmZnhvIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImtuLWNvbm5lY3Rvci1zb3VyY2UtaW50ZWdyYXRpb242ZTkyZmI4YmEyODkxNzM2OTNhNzU5ZDQ4ZWMzZTI1YiIsInVpZCI6IjRkMjVmMzBmLTA3NjItNGE4Yi05ODI5LWVmMmE2MzFiNGJmZiJ9fSwibmJmIjoxNzI5NTE0NzQ1LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6dGVzdC1ycnF4ZmZ4bzprbi1jb25uZWN0b3Itc291cmNlLWludGVncmF0aW9uNmU5MmZiOGJhMjg5MTczNjkzYTc1OWQ0OGVjM2UyNWIifQ.I5aJCDVmk9uvUnbGC8z4AV4GiTrGCqYndzMCje34zAVs5vykAFs_fn1zermgVF2IHY5ix1IgqUMCG6YgaAhSi5bpmDbsM2-OBmzpTsJvCOldoYAvGGkUbOZ-ah2jox10N1g04el-cFsy-lJgbhnSYZzdEjTSu-jGJkTROuwHDJkRXLVcMGxYRhbw_AT1IzN4UQ1mr4jleezXSwldjpHCB9tkyQtT6BCjTSVdjJoPLiysaPDbWBIITeWk77xz6ToNoxH0Ol-7icrCndt0hohjHWRLYrJb_m_TuxzOZvO3g7zpVw6Es_biB3hYhZkld9Uevutp2ZSzqPR4ouI8kpBJuw[jboss@kn-connector-source-integrationsource-kpcslidz-deployment-tg5k5 oidc]$

**Comment by christophd** [comment]
I have added the required OIDC support to the Camel Knative Http transport implementation. It will be available with Camel 4.9.0
See https://github.com/apache/camel/pull/16099

**Comment by matzew** [comment]
@christophd 

I am now getting: 
```
test-vbzhjbby integrationsource-iqjraxal-containersource-deployment-58494fk7f source 
test-vbzhjbby integrationsource-iqjraxal-containersource-deployment-58494fk7f source 2024-12-11 15:42:28,947 WARN  [org.apa.cam.com.tim.TimerConsumer] (vert.x-eventloop-thread-2) Error processing exchange. Exchange[4116EF59DDAF437-000000000000003C]. Caused by: [org.apache.camel.CamelException - HTTP operation failed invoking https://sink-hzuiktcp.test-vbzhjbby.svc.cluster.local with statusCode: 401, statusMessage: Unauthorized]: org.apache.camel.CamelException: HTTP operation failed invoking https://sink-hzuiktcp.test-vbzhjbby.svc.cluster.local with statusCode: 401, statusMessage: Unauthorized
test-vbzhjbby integrationsource-iqjraxal-containersource-deployment-58494fk7f source 	at org.apache.camel.component.knative.http.KnativeHttpProducer.lambda$process$0(KnativeHttpProducer.java:141)
test-vbzhjbby integrationsource-iqjraxal-containersource-deployment-58494fk7f source 	at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:402)
test-vbzhjbby integrationsource-iqjraxal-containersource-deployment-58494fk7f source 	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:384)
test-vbzhjbby integrationsource-iqjraxal-containersource-deployment-58494fk7f source 	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:362)
test-vbzhjbby integrationsource-iqjraxal-containersource-deployment-58494fk7f source 	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:329)
test-vbzhjbby integrationsource-iqjraxal-containersource-deployment-58494fk7f source 	at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:291)
test-vbzhjbby integrationsource-iqjraxal-containersource-deployment-58494fk7f source 	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$7(HttpContext.java:512)
test-vbzhjbby integrationsource-iqjraxal-containersource-deployment-58494fk7f source 	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
test-vbzhjbby integrationsource-iqjraxal-containersource-deployment-58494fk7f source 	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:252)
test-vbzhjbby integrationsource-iqjraxal-containersource-deployment-58494fk7f source 	at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:50)
test-vbzhjbby integrationsource-iqjraxal-containersource-deployment-58494fk7f source 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
test-vbzhjbby integrationsource-iqjraxal-containersource-deployment-58494fk7f source 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
test-vbzhjbby integrationsource-iqjraxal-containersource-deployment-58494fk7f source 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
test-vbzhjbby integrationsource-iqjraxal-containersource-deployment-58494fk7f source 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
test-vbzhjbby integrationsource-iqjraxal-containersource-deployment-58494fk7f source 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
test-vbzhjbby integrationsource-iqjraxal-containersource-deployment-58494fk7f source 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
test-vbzhjbby integrationsource-iqjraxal-containersource-deployment-58494fk7f source 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
test-vbzhjbby integrationsource-iqjraxal-containersource-deployment-58494fk7f source 	at java.base/java.lang.Thread.run(Thread.java:840)
test-vbzhjbby integrationsource-iqjraxal-containersource-deployment-58494fk7f source 
^C

```


that's w/ the camel 4.9

**Comment by christophd** [comment]
With #50 you should be able to use OIDC support as it is provided by Camel 4.9.0

Only thing to do is to specify these environment variables, e.g. on the IntegrationSource:
```
CAMEL_KNATIVE_CLIENT_OIDC_ENABLED=true
CAMEL_KNATIVE_CLIENT_OIDC_TOKEN_PATH=oidc/token
```

For more options to set (e.g. token caching) please look at the short introduction of this feature in the [README.adoc](https://github.com/knative-extensions/eventing-integrations/blob/c2dc10bd664fa24a26d94f0b7bcc3e9a688f874e/README.adoc#oidc-support)
